// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLySieuThiMini.Models;

#nullable disable

namespace QuanLySieuThiMini.Migrations
{
    [DbContext(typeof(ProductDBContext))]
    [Migration("20230731043858_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLySieuThiMini.Models.Bill", b =>
                {
                    b.Property<string>("billID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("empID")
                        .HasColumnType("int");

                    b.Property<string>("guestPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("totalPrice")
                        .HasColumnType("int");

                    b.HasKey("billID");

                    b.HasIndex("empID");

                    b.HasIndex("guestPhone");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("QuanLySieuThiMini.Models.BillDetail", b =>
                {
                    b.Property<string>("billID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("proID")
                        .HasColumnType("int");

                    b.Property<string>("billName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("billID", "proID");

                    b.HasIndex("proID");

                    b.ToTable("BillDetails");
                });

            modelBuilder.Entity("QuanLySieuThiMini.Models.Employee", b =>
                {
                    b.Property<int>("empID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("empID"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("posID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("empID");

                    b.HasIndex("posID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("QuanLySieuThiMini.Models.Guest", b =>
                {
                    b.Property<string>("guestPhone")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("guestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("guestPhone");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("QuanLySieuThiMini.Models.Position", b =>
                {
                    b.Property<string>("posID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("posName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("posID");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("QuanLySieuThiMini.Models.Product", b =>
                {
                    b.Property<int>("proID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("proID"));

                    b.Property<int>("cost")
                        .HasColumnType("int");

                    b.Property<int>("inventory")
                        .HasColumnType("int");

                    b.Property<string>("proName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("shelfID")
                        .HasColumnType("int");

                    b.Property<string>("typeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("proID");

                    b.HasIndex("shelfID");

                    b.HasIndex("typeID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("QuanLySieuThiMini.Models.ProductType", b =>
                {
                    b.Property<string>("typeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("typeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("typeID");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("QuanLySieuThiMini.Models.Shelf", b =>
                {
                    b.Property<int>("shelfID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("shelfID"));

                    b.Property<string>("shelfLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("shelfID");

                    b.ToTable("Shelves");
                });

            modelBuilder.Entity("QuanLySieuThiMini.Models.Bill", b =>
                {
                    b.HasOne("QuanLySieuThiMini.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("empID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLySieuThiMini.Models.Guest", "Guest")
                        .WithMany("Bills")
                        .HasForeignKey("guestPhone")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("QuanLySieuThiMini.Models.BillDetail", b =>
                {
                    b.HasOne("QuanLySieuThiMini.Models.Bill", "bill")
                        .WithMany("BillDetails")
                        .HasForeignKey("billID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLySieuThiMini.Models.Product", "product")
                        .WithMany("bill")
                        .HasForeignKey("proID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bill");

                    b.Navigation("product");
                });

            modelBuilder.Entity("QuanLySieuThiMini.Models.Employee", b =>
                {
                    b.HasOne("QuanLySieuThiMini.Models.Position", "Position")
                        .WithMany("employees")
                        .HasForeignKey("posID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("QuanLySieuThiMini.Models.Product", b =>
                {
                    b.HasOne("QuanLySieuThiMini.Models.Shelf", null)
                        .WithMany("products")
                        .HasForeignKey("shelfID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLySieuThiMini.Models.ProductType", "type")
                        .WithMany("products")
                        .HasForeignKey("typeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("type");
                });

            modelBuilder.Entity("QuanLySieuThiMini.Models.Bill", b =>
                {
                    b.Navigation("BillDetails");
                });

            modelBuilder.Entity("QuanLySieuThiMini.Models.Guest", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("QuanLySieuThiMini.Models.Position", b =>
                {
                    b.Navigation("employees");
                });

            modelBuilder.Entity("QuanLySieuThiMini.Models.Product", b =>
                {
                    b.Navigation("bill");
                });

            modelBuilder.Entity("QuanLySieuThiMini.Models.ProductType", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("QuanLySieuThiMini.Models.Shelf", b =>
                {
                    b.Navigation("products");
                });
#pragma warning restore 612, 618
        }
    }
}
